package com.demo.stream;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class DiffBetweenMapAndFlatMap {
	
	public static void main(String[] args) {
		
		ArrayList<String> fruit  =new ArrayList<>();
		fruit.add("Apple");
		fruit.add("mango");
		fruit.add("pineapple");
		fruit.add("kiwi");
		System.out.println("List Of Fruit- "+fruit);
		
		//lets use map to convert list of fruit
		
		List list =fruit.stream()
				   .map(s->s.length())
				   .collect(Collectors.toList());
		
		System.out.println("List generated by map-"+list);
		
		
		
	}

}
