package com.demo.stream;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class DiffBetweenMapAndFlatMap2 {
	
	public static void main(String[] args) {
		
//		   // making the arraylist object of List of Integer
//        List<List<Integer> > number = new ArrayList<>();
//       
//        // adding the elements to number arraylist
//        number.add(Arrays.asList(1, 2));
//        number.add(Arrays.asList(3, 4));
//        number.add(Arrays.asList(5, 6));
//        number.add(Arrays.asList(7, 8));
//       
//        System.out.println("List of list-" + number);
//        
//        //using flatmap() to flatten this list
//        
//        List<Integer> flatList =number.stream()
//        		                      .flatMap(list ->list.stream())
//        		                      .collect(Collectors.toList());
//        
//        System.out.println("List generated by flatMap "+flatList);
//        
        
		List<List<String>> string =new ArrayList<>();
		
		//adding the String elements to Arraylist
		string.add(Arrays.asList("rahul","suresh"));
		string.add(Arrays.asList("kishan","shriman"));
		string.add(Arrays.asList("gopal","ganesh"));
		string.add(Arrays.asList("suresh","mahesh"));
		string.add(Arrays.asList("raman","bala"));
		
		System.out.println("List of list -"+string);
		
		//using flatmap to flatten this list
		
		
		List<String> flattenList =string.stream().flatMap(stringlist->stringlist.stream()).collect(Collectors.toList());
		
		 System.out.println(flattenList);
		
	}

}
